### ISSUE TITLE
Which version of SDL ? 

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/tsdl#104]
@sanette, @zoggy or anyone following. What is your stance on the SDL version that should be supported, I'm getting requests that [need SDL 2.0.18](https://github.com/dbuenzli/tsdl/labels/needs-sdl-2.0.18) would it be ok to require that for the next release ?

**Comment by dbuenzli** [comment]
Also @zoggy if you are on linux could please do an `opam pin tsdl --dev` and verify that the new build stuff introduced by 116ab1febf4899bfbae works for you.

**Comment by zoggy** [comment]
I'm with SDK 2.0.20.

`opam pin tsdl --dev` works (it compiles and installs successfully), but when I have the new following error when building a bytecode:
```
/usr/bin/ld : /tmp/build_2a4a82_dune/ccpMwByS.o:(.data.rel.ro+0x1d38) : référence indéfinie vers « ocaml_tsdl_log_message »
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
```
did not investigate yet but does it ring a bell for you ?

**Comment by dbuenzli** [comment]
> did not investigate yet but does it ring a bell for you ?

It does: 

```
> ocamlobjinfo /Users/dbuenzli/.opam/4.14.2/lib/tsdl/tsdl.cma | grep 'Extra' 
Extra C object files: -lSDL2
Extra C options: -L/opt/homebrew/lib
Extra dynamically-loaded libraries: -ltsdl_stubs
```
I'm missing a `-ltsdl_stubs` in extra C object files for when we build a custom runtime system. Let me fix that.

**Comment by zoggy** [comment]
I made a simple repo exposing the problem here: https://github.com/zoggy/tsdl-text
(yet, there is a typo, I meant tsdl-test)
Simply run `dune build`
The error occurs when `modes` in `bin/dune` contains `byte_complete`. It compiles fine where `byte`is used instead.

**Comment by dbuenzli** [comment]
Thanks. Actually it was already showing up by adding `-custom` to the compilation of the [minimal example](https://github.com/dbuenzli/tsdl/blob/95fbf517e135551d20614ca32e37988cb6b1a9f5/test/min.ml#L4). 

I pushed a fix in 48b49ad66c5fd912c1671, it seems to work with the minimal example and your test on macOS. Can you please confirm it works on your side.

**Comment by zoggy** [comment]
Yes it works, thanks !

**Comment by dbuenzli** [comment]
So I decided to merge in these things needing 2.0.18.

**Comment by sanette** [comment]
sorry for not answering earlier; yes, it's a good idea to require 2.0.18, thanks for this
