### ISSUE TITLE
Sdl.blit_scaled

### ISSUE THREAD

**Issue by zapashcanon** [dbuenzli/tsdl#29]
Hi,

This issue is almost like #25, but for the `Sdl.blit_scaled` function.

Like stated [here](https://wiki.libsdl.org/SDL_BlitScaled) the two `SDL_Rect` can be `NULL`, but atm, the first one can't in tsdl: `val blit_scaled : src:surface -> rect -> dst:surface -> rect option -> unit result`.

Thanks. :)

**Comment by dbuenzli** [comment]
Closed by 5aee72459e881b3e6a9
