### ISSUE TITLE
load_wav_rw segfaults

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#32]
I'm trying to play some wav file. At the moment no success, the first bug is a segfault when calling
load_wav_rw. Looking at the source it seems that load_wav_rw has only 4 parameters while it should have 5 according to SDL doc. I changed this (below) and it seems to work better. (no segfault. No sound either, but this is probably another issue).

 let load_wav_rw =
   foreign "SDL_LoadWAV_RW"
-    (rw_ops @-> ptr audio_spec @-> ptr (ptr void) @-> ptr uint32_t @->
+    (rw_ops @-> int @-> ptr audio_spec @-> ptr (ptr void) @-> ptr uint32_t @->
      returning (some_to_ok (ptr_opt audio_spec)))

 let load_wav_rw ops spec =
   let d = allocate (ptr void) null in
   let len = allocate uint32_t Unsigned.UInt32.zero in
-  match load_wav_rw ops (addr (audio_spec_to_c spec)) d len with
+  match load_wav_rw ops 0 (addr (audio_spec_to_c spec)) d len with
   | Error _ as e -> e
   | Ok r ->
       let rspec = audio_spec_of_c (!@ r) spec.as_ba_kind in

**Comment by dbuenzli** [comment]
> No sound either, but this is probably another issue

Try to look for the test suite, sound should be produced. If you can PR a fix for this problem it would be appreciated.

**Comment by sanette** [comment]
Yes, the test_audio.ml works.
I've been doing a number of other tests today.
The tsdl_mixer binding by tokenrove does work for loading and playing wav files.
If I find something I will let you know of course.

**Comment by sanette** [comment]
Ah ! I got it working. It's just that my callback was wrong.
So finally it seems that one just has to fix load_wav_rw to get the correct number of arguments,
as in my first post.

**Comment by dbuenzli** [comment]
> one just has to fix load_wav_rw to get the correct number of arguments,

If you can PR the fix...

**Comment by sanette** [comment]
In case someone is interested, here is a working example that will play a WAV file from the command line.

https://github.com/sanette/tsdl/blob/fix%2332/test/read_wav.ml

**Comment by dbuenzli** [comment]
Closed by 7312da59e0d4ce9cfe0e0
