### ISSUE TITLE
playing audio: Fatal error: exception Ctypes_ffi_stubs.CallToExpiredClosure

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#36]
I've been playing with SDL audio interface, and often got this:

Fatal error: exception Ctypes_ffi_stubs.CallToExpiredClosure

I'm not sure if I do something wrong, or if really there is an ocaml object that is not well protected against Gc. I can reproduce using the program 
https://github.com/sanette/tsdl/blob/fix%2332/test/read_wav.ml
As it is, it works, but if you insert before line 95:
`  Gc.compact ();`
Then it crashes and the exception is raised.

**Comment by dbuenzli** [comment]
I think you may need to keep a reference on [this](https://github.com/sanette/tsdl/blob/fix%2332/test/read_wav.ml#L90) closure until it's no longer needed, this should be mentioned in the docs.

**Comment by sanette** [comment]
I'm not sure how to do this. I created a top-level global variable:
`let callback = ref None`
and then line 89 I save it with
```
callback := Some (play_through_once waveleft sound audio_spec.Sdl.as_silence);
  let audio_spec = {
      audio_spec with
      Sdl.as_callback = !callback
    } in
```

but I still have the same issue (CallToExpiredClosure).

I have to mention I use tsdl 0.9.1, maybe this makes a difference.

**Comment by dbuenzli** [comment]
In fact `tsdl` does [wrap](https://github.com/dbuenzli/tsdl/blob/7312da59e0d4ce9cfe0e03a452d0d4e885f3805a/src/tsdl.ml#L4617-L4627) your callback internally. So I guess a reference should be kept on the wrapper. 

Maybe the API should be: 

```
type as_callback
val : as_callback : (('a, 'b) bigarray -> unit) -> as_callback
```
with the wrapping done at that point and let the client know it has to keep a reference on as_callback values. Does that feel right @yallop ?

**Comment by sanette** [comment]
>So I guess a reference should be kept on the wrapper.
Right! I made a dirty hack in tsdl.ml to save wrap_cb in a global variable, and it works!

**Comment by yallop** [comment]
> Does that feel right @yallop ?

Yes, that does look reasonable.  I'm increasingly in favour of more explicit lifetime management for closures/callbacks passed to C, and explicit conversion from functions to callbacks is a step in that direction.
