### ISSUE TITLE
need SDL_PixelFormat

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#41]
Hi,

tsdl won't give you access to the SDL_PixelFormat field, because of memory ownership issues (says the source code). However some functions do need the format, like SDL_GetRGBA.

I don't really know how to workaround this. A possibility would be to allocate a new format with
Sdl.alloc_format (Sdl.get_surface_format_enum surface)
but it seems too much: probably too slow, and then you need to free the new format. Is it reasonable to include this in SDL_GetRGBA, which is typically a function that needs to run fast?
Any other idea?

San

**Comment by dbuenzli** [comment]
> to include this in SDL_GetRGBA, which is typically a function that needs to run fast?
> Any other idea?

If you need something fast you should not use `SDL_GetRGBA` you'll call to C and create a quadruplet on each call. It should be faster to create a surface with a known pixel depth, make sure you have what you want with `get_surface_format_enum` and perform bit twiddling in your code on the surface pixels mapped by a bigarray.

**Comment by sanette** [comment]
thanks for the tip. This is actually what I was doing initially before trying to use SDL_GetRGBA, in order to deal with the many different formats.
But you're right, it's probably more efficient to make sure at some point that all my surfaces have the same format.
