### ISSUE TITLE
Ocamlbuild fails (Ocb_stubblr)

### ISSUE THREAD

**Issue by srctxt** [dbuenzli/tsdl#42]
I'd like to run the tests. Ocb_stubblr is installed but it doesn't work.

ocamlbuild -use-ocamlfind tests.otarget

+ ocamlfind ocamlopt unix.cmxa -I /Users/bkb/.opam/4.02.3/lib/ocaml/ocamlbuild /Users/bkb/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/bkb/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 2, characters 5-16:
Error: Unbound module Ocb_stubblr
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.

**Comment by dbuenzli** [comment]
Use `topkg build`.

**Comment by jboadas** [comment]
When you try to install from opam you get a similar error:
```
[jboadas@devel maintests]$ opam install tsdl
The following actions will be performed:
  - install tsdl 0.9.5

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[tsdl] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of tsdl failed at "ocaml pkg/pkg.ml build --pinned
        false".

#=== ERROR while installing tsdl.0.9.5 ========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/pkg.ml build --pinned false
# path         /home/jboadas/.opam/4.02.3/build/tsdl.0.9.5
# compiler     4.02.3
# exit-code    2
# env-file     /home/jboadas/.opam/4.02.3/build/tsdl.0.9.5/tsdl-7991-1872ec.env
# stdout-file  /home/jboadas/.opam/4.02.3/build/tsdl.0.9.5/tsdl-7991-1872ec.out
# stderr-file  /home/jboadas/.opam/4.02.3/build/tsdl.0.9.5/tsdl-7991-1872ec.err
### stdout ###
# No such package: ocb-stubblr.topkg
### stderr ###
# File "./pkg/pkg.ml", line 12, characters 27-48:
# Error: Unbound module Ocb_stubblr_topkg
# pkg.ml: [ERROR] No package description found. A syntax error may have occured
#                 or did you forget to call Topkg.Pkg.describe ?

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install tsdl 0.9.5
No changes have been performed
[jboadas@devel maintests]$ opam install ocb-stubblr
[NOTE] Package ocb-stubblr is already installed (current version is 0.1.1).
```

**Comment by dbuenzli** [comment]
That's weird can't reproduce on macos, could you please post the output of: 

```
cat $(opam config var ocb-stubblr:lib)/META
> ocamlfind list | grep ocb
ocb-stubblr         (version: 0.1.1)
ocb-stubblr.topkg   (version: 0.1.1)
```

**Comment by dbuenzli** [comment]
(I suspect you forgot to `eval $(opam config env)` and the build is picking up a system installed `ocamlfind`)

**Comment by jboadas** [comment]
Yes you are right, sorry for that I am doing my first steps with Ocaml.
Thanks.

**Comment by dbuenzli** [comment]
No problem. But OTOH that's a bit strange because I believe what I told you is wrong... IIRC the compilation should occur in an environment that has `$(opam config env)`. Doing `$(opam config env)` is to make that envrionment available for your own out-of-opam builds.

**Comment by dbuenzli** [comment]
I don't think there's any problem specific with `tsdl` here. Feel free to continue the discussion if you think otherwise.

**Comment by dbuenzli** [comment]
@srctxt I have updated the wrong test build instructions in ff7e1bfd5f500f. Thanks for the report.
