### ISSUE TITLE
Support for 2.0.7

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/tsdl#46]
Go through the [release notes](https://hg.libsdl.org/SDL/file/2088cd828335/WhatsNew.txt) and add bindings to the new entry points and enumerants.

**Comment by fccm** [comment]
Updated link for 2.0.8, 2.0.9 and 2.0.10:
https://hg.libsdl.org/SDL/file/3b03741c0095/WhatsNew.txt

**Comment by fccm** [comment]
Made a gist with the output of the command
```
diff -Naur SDL2-2.0.9/include/ SDL2-2.0.10/include/ 
```
https://gist.github.com/fccm/265db754b656b4e95f1d20cd4e2a59b4

**Comment by fccm** [comment]
https://github.com/fccm/tsdl/commits/master

I wrapped some of the new functions from SDL2-2.0.10:
- `SDL_RenderDrawPointF()` as `Sdl.render_draw_point_f`
- `SDL_RenderDrawLineF()` as `Sdl.render_draw_line_f`

and the structures:
- `SDL_FRect` from header `SDL2/SDL_rect.h` as `module FRect`
- `SDL_FPoint` from header `SDL2/SDL_rect.h` as `module FPoint`

I hope the naming is right for you.

**Comment by fccm** [comment]
Made another gist with the output of the command:
```
diff -Naur SDL2-2.0.10/include/ SDL2-2.0.12/include/
```
https://gist.github.com/fccm/8b1d656881960c4e04752cc05320f2a1

(it seems there is no `SDL2-2.0.11`)

**Comment by dbuenzli** [comment]
> * `SDL_FRect` from header `SDL2/SDL_rect.h` as `module FRect`
> * `SDL_FPoint` from header `SDL2/SDL_rect.h` as `module FPoint`

For [least surprise](https://discuss.ocaml.org/t/module-files-module-names-and-capitalization/1025/2) I don't want multiple capitals in module names. Either we follow the [tsdl convention](https://erratique.ch/software/tsdl/doc/Tsdl/index.html#naming) religiously and that should be `F_rect` and `F_point` or, if that looks too busy to read, we could go for `Frect` and `Fpoint`.

(I didn't look at your patches, either PR or send them by email when they are ready)

**Comment by fccm** [comment]
For better consistency, what would you think about `Rectf` and `Pointf`,
or `Rect_f` and `Point_f` ?

**Comment by fccm** [comment]
Do you want a PR for the work already done, so that other people can review/test it? Or do you prefer a PR at the end?

**Comment by dbuenzli** [comment]
When you are confident it's ready to be merged please.

**Comment by dbuenzli** [comment]
> For better consistency, what would you think about `Rectf` and `Pointf`,
> or `Rect_f` and `Point_f` ?

Which consistency ? That doesn't look consistent with sdl's API. Just follow the tsdl convention please, it makes it obvious to translate from C sdl code out there.

**Comment by fccm** [comment]
OK, I'll make a PR right now then.

Consistency with both the function names that put the 'f' at the end, and also to keep the case of the original (int) structures. But this is mainly a question of taste, and everyone has a different taste. But you're the maintainer so I'll follow you!

So which one you want? `F_rect` and `F_point`, or `Frect` and `Fpoint`?

**Comment by dbuenzli** [comment]
> So which one you want? `F_rect` and `F_point`, or `Frect` and `Fpoint`?

Your call, write some code that uses the stuff and chose the one you prefer to read.

**Comment by dbuenzli** [comment]
In general people gradually adding what is missing seems to work.

Regarding the discusion about `SDL_F{Rrect,Point}` @ffcm added them in b6929fee19626a6a.

Let's close this.
