### ISSUE TITLE
Track possible upstream documentation improvements.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/tsdl#47]
It seems that the wiki that held the documentation to which `tsdl`s documentation links is no longer being updated for the latest entry points. This [upstream issue](https://bugzilla.libsdl.org/show_bug.cgi?id=3841) when solved could provide an alternative to link to in `tsdl`s docs.

**Comment by Octachron** [comment]
It looks like the upstream documentation has finally been [updated](https://wiki.libsdl.org/SDL_Vulkan_CreateSurface?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29).

**Comment by dbuenzli** [comment]
As far as I undersand the resolution here https://github.com/libsdl-org/SDL/issues/2627 they kept the same doc structure which means our extensive doc linking into their wiki continues to work; a very good idea. 

I added the docs links for vulkan in 6d3cc61a29a880115da
