### ISSUE TITLE
Backward compatibility?

### ISSUE THREAD

**Issue by LemonBoy** [dbuenzli/tsdl#50]
The `libsd2-dev` package on debian stable is stuck at version 2.0.5 and at the moment I'm unable to compile tsdl due to some missing enums, the only solution I see is to hack away all the new definitions and pin my own local version.
I was wondering if it'd be possible to have backwards compatibility to some degree either with some `ifdef`s (ugh, I know) or by shipping the sdl headers so that tsdl at least compiles on older systems.

**Comment by dbuenzli** [comment]
I'm afraid we don't have enough ressources allocated to this project for providing that level of support, it's already good if we manage to follow the latest version. If someone wants to work and implement such a system, PR are welcome. 

I suggest you either install your own copy of sdl2 or simply install an earlier version of `tsdl` that supports 2.0.5 see the release notes.

Sorry.
