### ISSUE TITLE
tsdl fails to build

### ISSUE THREAD

**Issue by Armael** [dbuenzli/tsdl#51]
`opam install tsdl` fails with the following error log (I'm using opam 2 and ocaml 4.06.0):

```
ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package ocb-stubblr myocamlbuild.ml /home/armael/.opam/current/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind ocamlc -g -thread -c src/tsdl_stubs.c
mv tsdl_stubs.o src/tsdl_stubs.o
ocamlfind ocamlmklib -o src/tsdl -ldopt -Wl,-no-as-needed '-pthread -lSDL2' src/tsdl_stubs.o
+ ocamlfind ocamlmklib -o src/tsdl -ldopt -Wl,-no-as-needed '-pthread -lSDL2' src/tsdl_stubs.o
ocamlfind: unknown option '-pthread -lSDL2'.
usage: ocamlfind ocamlmklib [options] file ...

<snip>

Command exited with code 2.
pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
     '-build-dir' '_build' '-plugin-tag' 'package(ocb-stubblr)' 'opam'
     'pkg/META' 'CHANGES.md' 'LICENSE.md' 'README.md' 'src/tsdl.a'
     'src/tsdl.cmxs' 'src/tsdl.cmxa' 'src/tsdl.cma' 'src/tsdl.cmx'
     'src/tsdl.cmi' 'src/tsdl.mli' 'src/tsdl_consts.cmx' 'src/tsdl_top.a'
     'src/tsdl_top.cmxs' 'src/tsdl_top.cmxa' 'src/tsdl_top.cma'
     'src/tsdl_top.cmx' 'src/tsdl_top_init.ml' 'src/dlltsdl.so'
     'src/libtsdl.a' 'README.md' 'CHANGES.md' 'test/min.ml' 'test/minc.c']: exited with 10
```

**Comment by dbuenzli** [comment]
Can't reproduce on macos with latest `ocamlbuild` and `ocamlfind`.

**Comment by Armael** [comment]
Umm, weird. On my computer (Linux) it's failing with ocamlfind 1.8.0, and ocamlbuild 0.12.0.

**Comment by Firobe** [comment]
Same error here with ocamlfind 1.8.0 and ocamlbuild 0.12.0 (Arch Linux).
It seems that there is a problem with the `-ldopt` parameter, which is `-Wl,-no-as-needed '-pthread -lSDL2'` but should be `'-Wl,-no-as-needed -pthread -lSDL2'`.
Removing completely `-Wl,-no-as-needed` via `myocamlbuild.ml` is a temporary fix.

**Comment by Armael** [comment]
For the record I'm also using Archlinux.

**Comment by dbuenzli** [comment]
> Removing completely -Wl,-no-as-needed via myocamlbuild.ml is a temporary fix.

That's a fix you get by chance...

I think the issue is with `ocb-stubblr`. It [seems](https://github.com/pqwy/ocb-stubblr/blob/34dcbede6b51327172a0a3d83ebba02843aca249/src/ocb_stubblr.ml#L226-L232) to use `--libs` to lookup flags to pass to `ocamlmklib`, the latter is fine with `-l` options but seems not to be with `-pthreads`  for the latter `-ldopt` need to be prefixed.

I'll open an issue upstream, that's were the fix should go.

**Comment by rand00** [comment]
I also have the problem on Arch

**Comment by trefis** [comment]
Aaaaand ping.

**Comment by mbernat** [comment]
A partial workaround until the upstream gets fixed: revert the commit that added ocb_stubblr. This makes the thing compile again but tests fail with:
`Fatal error: exception File "test/test.ml", line 764, characters 6-12: Assertion failed`

**Comment by dbuenzli** [comment]
I think I will do what @mbernat suggests. Quite busy at the moment though if anyone wants to PR before I can get back to it, please do.

**Comment by dbuenzli** [comment]
Ok so did so on trunk could one of the affected person confirm me that master builds by: 

```
opam pin add tsdl --dev 
```

**Comment by Armael** [comment]
I can confirm that it now works. Thanks!

(The pinning command gave me a couple puzzling warnings though, see below)

```
[tsdl.0.9.6] synchronised from git+http://erratique.ch/repos/tsdl.git
[WARNING] Failed checks on tsdl package definition from source at git+http://erratique.ch/repos/tsdl.git:
    error 42: The 'dev-repo:' field doesn't use version control. You should use URLs of the form "git://", "git+https://", "hg+https://"...
  warning 49: The following URLs don't use version control but look like version control URLs: "https://erratique.ch/repos/tsdl.git"
    error 57: Synopsis and description must not be both empty
tsdl is now pinned to git+http://erratique.ch/repos/tsdl.git (version 0.9.6)
[... and then it installs properly]
```

**Comment by dbuenzli** [comment]
Thanks Armael ! 

Regarding the warnings I fixed 42 but 57 is really a bad default by the opam devs. My repo `opam` file never have a synopsis and description file since I generate those from the README.md.
