### ISSUE TITLE
How to get `pixel_format` from a surface or from `Pixel.format_enum`?

### ISSUE THREAD

**Issue by kenranunderscore** [dbuenzli/tsdl#55]
Sorry for the vague beginner-level question, but I'm trying to learn SDL and OCaml simultaneously and stumbled over this when I tried to do the second [Lazy Foo lesson](https://lazyfoo.net/tutorials/SDL/01_hello_SDL/index2.php).

I used `Sdl.get_window_surface my_window` to get an `Sdl.surface` object. Then I can (as far as I understand) call `Sdl.get_surface_format_enum` to get the format as `Pixel.format_enum`. To use `Sdl.map_rgb` as in the example, I need something of type `pixel_format` though. How can I get there from what I have? (I got it to work by using `Sdl.alloc_format`, but that doesn't seem right to me, as I don't want to allocate a new format at all, but rather just pass a reference to an existing one).

Thanks!

**Comment by dbuenzli** [comment]
Hello, please ask these questions on http://discuss.ocaml.org where there are people willing to help newcomers and answers may benefit a wider audience.

Thanks.
