### ISSUE TITLE
test.native doesn't pass with SDL 2.0.10

### ISSUE THREAD

**Issue by fccm** [dbuenzli/tsdl#58]
While willing to test [PR 48](https://github.com/dbuenzli/tsdl/pull/48) about MessageBox, I found that the test `./_build/test/test.native` doesn't pass.
I'm using SDL 2.0.10:
```
Testing version
 Version: SDL 2.0.10
 Revision: hg-12952:bc90ce38f1e2
 Revision number: 12952
```
The error is the assert at lines 764 that raises, and if I comment it then the assert at line 765 also raises, if I comment this second line, then the test passes until the end.
lines 764 and 765 of `test/test.ml` are:
```
      assert (Sdl.get_window_grab w);
      assert (Sdl.unsafe_ptr_of_window w = w');
```
This was compiled with sguillia's 89965fe73c1d commit.

**Comment by dbuenzli** [comment]
It's unclear what you are reporting here. Are you reporting about a bug that exists on master or about a bug that exists in #48 ?

**Comment by fccm** [comment]
I was just willing to test PR 48, but the problem doesn't seem to be related to sguillia's last commits.
I just tested with 3ba92bf37a3c02 the problem is the same.

**Comment by fccm** [comment]
sguillia is adding a new parameter for function `show_message_box`:
https://github.com/dbuenzli/tsdl/pull/48/commits/ea13dcbfc7982d99f1e411076abfd86ad9377475

The assert failure in `test.ml` is with calling functions `Sdl.get_window_grab` and `Sdl.unsafe_ptr_of_window`. There is no relations.

**Comment by dbuenzli** [comment]
I can't reproduce on macOS. Which platform are you using ? Also are you using the release tarball ?

**Comment by fccm** [comment]
I'm using Mageia Linux.
I've installed this rpm:
http://svnweb.mageia.org/packages/cauldron/sdl2/current/SPECS/sdl2.spec?view=markup
it seems that it is not patched, so we can maybe consider it as a plain vanilla version.

**Comment by lwitzman** [comment]
The grabbed window tests have never passed for me on GalliumOS with any version of SDL2 compiled from source. SetWindowGrab appears to do nothing and GetGrabbedWindow returns null, even in C test programs I wrote.

**Comment by dbuenzli** [comment]
Thanks @lwitzman for the information. I think I'll simply disable this test.
