### ISSUE TITLE
How to generate Tsdl_consts?

### ISSUE THREAD

**Issue by MargaretKrutikova** [dbuenzli/tsdl#59]
I was trying to use the bindings but `Tsdl_consts` file is missing and is supposed to be auto-generated.
What are the steps to generate the file?

Thanks!

**Comment by dbuenzli** [comment]
Nothing special. Just do a `topkg build` or `pkg/pkg.ml build` if you don't have `topkg-care` installed.

**Comment by MargaretKrutikova** [comment]
Great, thanks for the quick response! 😄
