### ISSUE TITLE
Runtime error on Windows

### ISSUE THREAD

**Issue by tjammer** [dbuenzli/tsdl#60]
I cannot run the examples on Windows, they all fail with a runtime error `Fatal error: exception Dl.DL_error("dlsym: no such symbol")`

From what I could google, this comes from ctypes-foreign and/or libffi. Is this a general problem on Windows or am I doing something wrong here? I'm using ocaml on Windows as described [here](https://fdopen.github.io/opam-repository-mingw/installation/)

**Comment by dbuenzli** [comment]
> Is this a general problem on Windows or am I doing something wrong here?

I have no idea and no Windows. Unfortunately you could try to fish for more useful answers on https://discuss.ocaml.org/ (make sure to mention how you install `tsdl` and which invocations lead to this error).

**Comment by dbuenzli** [comment]
I'm afraid there's not much I can do here at the moment. Feel free to follow up with details but I'm closing this for now.
