### ISSUE TITLE
automatically select good version

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#65]
On Ubuntu 16.04 (Xenial), which ships SDL 2.0.4, the current tsdl will not compile, but it works great with tsdl.0.9.2.
Is there a way to make the package automatically select the appropriate version?

**Comment by dbuenzli** [comment]
I think one way would be to make the `conf-sdl` package versions follow (and checks) SDL versions (I'm no longer sure how to do that, someone like @kit-ty-kate likely knows, or try to checkout other `conf-*` packages). 

That is have a `conf-sdl2.2.0.4,`. The `opam` file for `tsdl.0.9.2` could then mention:
```
"conf-sdl" {<= "2.0.4"}
```
and those after (with `XX` the actual appropriate version, I'm unsure which one it is).
```
"conf-sdl" {> "2.0.XX"}
```
Most of this should happen at the opam repository level and I personally don't have the time to work on this. But I'm happy to be `cc`'s in discussions.

**Comment by dbuenzli** [comment]
I think this is a packaging issue and nothing specific is needed here. So I'm closing this. Feel free to continue the discussion in this issue and/or cc me in discussions elsewhere about that.
