### ISSUE TITLE
Need help for surfaces manipulations

### ISSUE THREAD

**Issue by thibautbenjamin** [dbuenzli/tsdl#68]

**Comment by thibautbenjamin** [comment]
Sorry I misclisked. I thought of opening an issue, but decided my problem was more of me not understanding something, and that was probably better suited to a website like stackoverflow. Someone with administrative privileges can delete this issue

**Comment by dbuenzli** [comment]
No problem. If you want to talk with OCaml programmers, questions are welcome on https://discuss.ocaml.org/

**Comment by thibautbenjamin** [comment]
Thanks I posted my question there as well as on SO
