### ISSUE TITLE
test.native failing on Arch Linux

### ISSUE THREAD

**Issue by guygastineau** [dbuenzli/tsdl#69]
Hi, I installed the latest version of you library with OPAM, and I downloaded your repo to run the tests.  Everything seems to work except I can't pass `test.native`.

It fails the `Testing OpenGl` contexts test module with the following output:
```
Testing OpenGL contexts
 Context version: 2.1
 Context is EGL: false
 Context core: false compatibility: false ES: false
Fatal error: exception File "test/test.ml", line 865, characters 21-27: Assertion failed
```

I don't really understand what is wrong here... :/

Below is a list of all the opengl packages I have installed:

```
local/freeglut 3.2.1-2
    Provides functionality for small OpenGL programs
local/ftgl 2.4.0-2
    OpenGL library to use arbitrary fonts
local/glew 2.2.0-2
    The OpenGL Extension Wrangler Library
local/glslang 11.0.0-1
    OpenGL and OpenGL ES shader front end and validator
local/glu 9.0.1-2
    Mesa OpenGL Utility library
local/libepoxy 1.5.5-1
    Library handling OpenGL function pointer management
local/mesa 20.3.1-1
    An open-source implementation of the OpenGL specification
```

I don't really understand what `EGL` is, but if I search for it with pacman I find that I have the following installed:

```
local/eglexternalplatform 1.1-2
    EGL External Platform interface
local/gegl 0.4.26-1
    Graph based image processing framework
local/libglvnd 1.3.2-1
    The GL Vendor-Neutral Dispatch library
```

If anyone can help me with this I would really appreciate it ;)

**Comment by dbuenzli** [comment]
[This is](https://github.com/dbuenzli/tsdl/blob/master/test) the test that is failing. I suspect it also fails in plain C. If the rest seems to be working then no need to worry.

**Comment by guygastineau** [comment]
Thanks for the quick reply.  Indeed `tsdl` is working with [bogue](https://github.com/sanette/bogue) now.

I also have a local patch on `bogue`, so it can use the most recent version of your `tsdl` ;)

Anyway, I assumed that the problem was on my end, and that it also didn't matter too much.  Thank you for confirming that for me!
