### ISSUE TITLE
SDL_KEYMAPCHANGED missing in enums

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#76]
The enum corresponding to `keymap_changed` seems to be missing, is there any particular reason for this?
See
https://github.com/dbuenzli/tsdl/blob/9e089594f3f85757df2deab396cf11e894feaf4e/src/tsdl.ml#L4441
and
https://github.com/dbuenzli/tsdl/blob/9e089594f3f85757df2deab396cf11e894feaf4e/src/tsdl.ml#L4459

**Comment by dbuenzli** [comment]
I don't know. Maybe it didn't exist when I did the bindings.

**Comment by sanette** [comment]
but `keymap_changed` does exist. 
https://github.com/dbuenzli/tsdl/blob/9e089594f3f85757df2deab396cf11e894feaf4e/src/tsdl.ml#L4241

I can make a PR if you like

**Comment by sanette** [comment]
you're right. Comparing with a reasonably old version of SDL (2.0.9) 
https://github.com/libsdl-org/SDL/blob/release-2.0.9/include/SDL_events.h

 here are the missing enums:
```
SDL_KEYMAPCHANGED
SDL_DROPTEXT
SDL_DROPBEGIN
SDL_DROPCOMPLETE
SDL_AUDIODEVICEADDED
SDL_AUDIODEVICEREMOVED
SDL_RENDER_TARGETS_RESET
SDL_RENDER_DEVICE_RESET
```

they all exist as `event_type` values in `tsdl`, so it's easy to correct I guess

**Comment by dbuenzli** [comment]
@zoggy added the drop cases in a85f7be63355f6fda368ea, commit 48c7e35758591a1998 does the rest.
