### ISSUE TITLE
bigarray_compat needed for ocaml 4.07 (tsdl.0.9.8)

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#81]
Hi, 

Running the tests gives:
```
Error: No implementations provided for the following modules:
         Bigarray referenced from test/test.cmx
```

This is easily solved by adding "bigarray-compat" to the `depends` field of the `opam` file,
and adding `module Bigarray = Bigarray_compat` at various places in the code.

Another solution would be to raise the lower bound to "ocaml" {>= "4.08.0"} (as is done for tsdl.0.9.9) but maybe this is a bit harsh.

What do you think?
See https://github.com/ocaml/opam-repository/pull/22543

**Comment by dbuenzli** [comment]
> Another solution would be to raise the lower bound to "ocaml" {>= "4.08.0"} (as is done for tsdl.0.9.9) 

As far as I can see this is already the case in the `opam-repository`.

> but maybe this is a bit harsh.

Nothing harsh in leaving old compilers behind, bugs do get fixed meanwhile and except for the 5 jump it's always backward compatible. 

What you propose would only add cruft to the system for very little returns.

**Comment by sanette** [comment]
> As far as I can see this is already the case in the `opam-repository`.

what do you mean? I don't see this in

https://github.com/ocaml/opam-repository/blob/master/packages/tsdl/tsdl.0.9.8/opam

**Comment by dbuenzli** [comment]
My bad. I did  an `opam info tsdl.0.9.8 --raw`, but it seems I didn't clear my pin when I released `0.9.9` and it counter-intuitively seems to return the pin opam file.

In any case is this a bug for people using `tsld` or simply affecting the test suite ?

**Comment by sanette** [comment]
It's a problem for users too, for instance under 4.07 if I try to compile the "minimal example":
```ocaml
open Tsdl

let main () = match Sdl.init Sdl.Init.video with
| Error (`Msg e) -> Sdl.log "Init error: %s" e; exit 1
| Ok () ->
    match Sdl.create_window ~w:640 ~h:480 "SDL OpenGL" Sdl.Window.opengl with
    | Error (`Msg e) -> Sdl.log "Create window error: %s" e; exit 1
    | Ok w ->
        Sdl.delay 3000l;
        Sdl.destroy_window w;
        Sdl.quit ();
        exit 0

let () = main ()
```
I get
```bash
$ ocamlfind ocamlc -thread -package tsdl -linkpkg -o min.byte min.ml
File "min.ml", line 1:
Error: Required module `Bigarray' is unavailable
```

**Comment by dbuenzli** [comment]
Well it just means that before 4.07 you need to add `-package bigarray` no ? That doesn't seem like a big deal.

**Comment by sanette** [comment]
yes I think you're right

**Comment by sanette** [comment]
I confirm the compilation works with -package bigarray
This could be added to the doc (also mentioning the -thread flag, which seems to be required too)

Is there a way to prevent the test suite to fail in this case?

**Comment by dbuenzli** [comment]
I'm sorry but I don't have the time to micromanage all this. I provide limited free support only for the latest version of each my software.

**Comment by sanette** [comment]
Sure I understand, I will pass the message to the opam maintainers
