### ISSUE TITLE
Example no longer works (no window opens) (macos)

### ISSUE THREAD

**Issue by anentropic** [dbuenzli/tsdl#82]
The example here:

https://erratique.ch/software/tsdl/doc/Tsdl/index.html#opengl_2

I am on macos 13.0.1 (and apple silicon).  I have an opam switch for 4.14.0 with just tsdl installed.

I have pasted the example code into a file `min.ml`.

Firstly, when I run the command `ocamlfind ocamlopt -package tsdl -linkpkg -o min.native min.ml` I get an error:
```
ocamlfind: [WARNING] Package `threads': Linking problems may arise because of the missing -thread or -vmthread switch
```

If I correct that and run `ocamlfind ocamlopt -package tsdl -thread -linkpkg -o min.native min.ml` then it compiles ok.

Then if I run the resulting file `./min.native`, just nothing happens.  Nothing is echoed, no window opens, after a couple of seconds the terminal prompt returns.

**Comment by anentropic** [comment]
if I adjust this line `Sdl.delay 3000l;` with a bigger number it takes longer to return to the terminal prompt.

So nothing is echoed because it's taking the `Ok` code path. But there is no window.

**Comment by dbuenzli** [comment]
Indeed it also no longer seem to work here. I tried to replace the delay by 

```
ignore (Sdl.wait_event_timeout None 3000);
```
and it works.

**Comment by anentropic** [comment]
I tried:
```ocaml
open Tsdl

let main () = match Sdl.init Sdl.Init.video with
| Error (`Msg e) -> Sdl.log "Init error: %s" e; exit 1
| Ok () ->
    match Sdl.create_window ~w:640 ~h:480 "SDL OpenGL" Sdl.Window.opengl with
    | Error (`Msg e) -> Sdl.log "Create window error: %s" e; exit 1
    | Ok w ->
        ignore (Sdl.wait_event_timeout None 3000);
        Sdl.destroy_window w;
        Sdl.quit ();
        exit 0

let () = main ()
```
but no window opens for me

also tried with `10000` timeout

**Comment by dbuenzli** [comment]
Keep the Sdl.delay afterwards maybe you have an event in the queue.

**Comment by anentropic** [comment]
still nothing 😞 

I'm expecting to see 640x480 window come up on my screen for a few seconds, right?

**Comment by dbuenzli** [comment]
> I'm expecting to see 640x480 window come up on my screen for a few seconds, right?

Indeed. I'm on 12.6.1 and apple decided I cannot upgrade to 13 so I can't really see if that's the reason.

**Comment by dbuenzli** [comment]
Thanks @ul for confirmation, very much appreciated. Could you please confirm that [this sample code](https://github.com/dbuenzli/tsdl/blob/master/test/min.ml) that I just pushed works. It's more inline with the non working example.

**Comment by ul** [comment]
Thank you for updating the example; it does work as intended on macOS 13.1, at least on my machine.

**Comment by dbuenzli** [comment]
Thanks. @anentropic feel free to add more details if you find your problem. But for the time being I'll consider that to be fixed.
