### ISSUE TITLE
SDL_GameControllerAddMappingsFromFile is a macro

### ISSUE THREAD

**Issue by jonahbeckford** [dbuenzli/tsdl#85]
The following:
https://github.com/dbuenzli/tsdl/blob/e61b803912415e1d30085e0437dee06d50ea5bee/src/tsdl.ml#L3624-L3626

will give:

```
# require "tsdl.top";;
# Tsdl.Sdl.game_controller_add_mapping_from_file "hi";; 
Exception:
Dl.DL_error
 "dlsym: no such symbol: \"SDL_GameControllerAddMappingsFromFile\"".
```

I'm doing this on Windows MSVC, but other SDL2 functions work (after upcoming PRs), yet the code:
https://github.com/libsdl-org/SDL/blob/c0445c23bf94b21b1500bd91d4bf6d6fe2ee743f/include/SDL_gamecontroller.h#L167-L172

shows `SDL_GameControllerAddMappingsFromFile` is a macro.

Not sure what the right solution is (polyfill or remove the binding).

**Comment by dbuenzli** [comment]
Thanks. I'll remove the binding. The equation is simple enough for users to expand it themselves.
