### ISSUE TITLE
Use of `result` type prevents polymorphic variants from being useful

### ISSUE THREAD

**Issue by iitalics** [dbuenzli/tsdl#93]
In this package, the following result alias is used:
```ocaml
type nonrec 'a result = ('a, [ `Msg of string ]) result
```

This type is not polymorphic in the error case -- it is monomorphic. This makes it inflexible when attempting to compose it with paths that may return different error variants:

```ocaml
let ( let* ) = Result.bind ;;

let main () = 
  let* () = Sdl.init Sdl.Init.video in
  Error(`Other_condition) (* <- this is a type error *)
```

This library should be changed so that the type signatures return `('a, [> Msg of string])` which allows programmers to make use of polymorphic variants. As of now the use case is completely wasted, they have worse runtime representation than `('a, string) result`, and they require the programmer to tediously wrap calls e.g.
```ocaml
(* this function is actually polymorphic *)
let init2 x = match Sdl.init x with Ok(y) -> Ok(y) | Error(`Msg m) -> Error(`Msg m) 
```

**Comment by dbuenzli** [comment]
> This library should be changed so that the type signatures return `('a, [> Msg of string])` which allows programmers to make use of polymorphic variants.

Experience shows and manuals [tell](https://v2.ocaml.org/manual/polyvariant.html#s:polyvariant-weaknesses) that having open variants by default is not a good idea. In general it's better to use [a combinator](https://erratique.ch/software/rresult/doc/Rresult/R/index.html#val-open_error_msg) to open the variant at the point where you want to compose it with another one.
